title: Mijail Rondon
email: yo@mijailr.com
description: 'Blog <a href="https://twitter.com/mijailr">@MijailR</a>'
tagline: "Developer, hacker, and free software activist."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mijailr.com" # the base hostname & protocol for your site
twitter_username: mijailr
github_username:  mijailr
paginate: 5
permalink: pretty
markdown: kramdown
highlighter: rouge
paginate_path: "page:num"
category_dir: "category"
category_layout: "index.html"
plugins:
  - jekyll-sitemap
  - jekyll-paginate-category
sass:
  load_paths:
    - _scss
    - node_modules
  style: compressed

