title: Mijail Rondon
email: yo@mijailr.com
tagline: "Senior Developer Consultant"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mijailr.com" # the base hostname & protocol for your site
main_username: mijailr
keybase_username:  mijailr
paginate: 10
permalink: pretty
markdown: kramdown
paginate_path: "page:num"
category_dir: "category"
category_layout: "index.html"
collections:
  days_of_code:
    output: true
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-paginate-category
sass:
  load_paths:
    - _scss
    - node_modules
  style: compressed

